### ISSUE TITLE
Getting instances by zone returns nothing

### ISSUE THREAD

**Issue by dexma-dev** [exoscale/python-exoscale#47]
Hi everybody,

i have just started using the python wrapper for the exoscale api but already came across an issue.
I am not able to retrieve all instances by zone, as the generator that is returned is empty.

```
zones = exo.compute.list_zones()

for zone in zones:
    instances = exo.compute.list_instances(zone=zone)
    for x in instances:
        print(x)
```

In my case `instances` is just an empty generator.
Any idea what is happening here and where the problem is?

_exoscale version: 0.8.0
python version: 3.10_

**Comment by brutasse** [comment]
Hi @dexma-dev, if you're just getting started can I suggest using the bindings for our v2 API? The namespaces you're using will be deprecated in the near future since they target our legacy API.

It's not clear what is wrong with your code but here is how to achieve what you want with our v2 API:

```python
from exoscale.api.v2 import Client

key = "…"
secret = "…"

c = Client(key, secret)  # this creates a client for the default zone

for zone in c.list_zones()["zones"]:
    c = Client(key, secret, zone=zone["name"])
    for instance in c.list_instances()["instances"]:
        print(instance)
```

You basically have 1 client for each zone you work in. Hope this helps!

**Comment by brutasse** [comment]
Indeed if your key is unrestricted it's not a perms issue. Can you get in touch with support so that we can have a closer look via a private channel?

**Comment by dexma-dev** [comment]
I was abl to accomplish what i wanted after using the V2 bindings and using the following api routes:

https://exoscale.github.io/python-exoscale/v2.html#exoscale.api.v2.Client.list_instance_types
https://exoscale.github.io/python-exoscale/v2.html#exoscale.api.v2.Client.get_instance_type

Closing.

**Comment by brutasse** [comment]
Thanks @dexma-dev!
