### ISSUE TITLE
Use better versioning in the future

### ISSUE THREAD

**Issue by mlec1** [exoscale/python-exoscale#55]
Dear Exoscale Team,

It would be great if you could stick to proper versioning practices to ensure clarity and consistency. Specifically, use major updates for significant changes and improvements, and use minor updates for smaller, incremental adjustments.

I noticed that in the v0.8.0 update, there were some substantial changes included in what is typically considered a minor update, but totally deprecates the old client. I think it is a breaking change, and it should have been a major version update. It is especially important for other project which depends on these dependencies and have automated updates with Renovate or Dependabot for example. It plays also a role in prioritizing and managing our development efforts effectively.

I know the version 0.8.0 got released a few months ago already, but as I was working on the documentation, I noticed that a version 0.9.0 is planned. I wanted to raise this issue in case the version 0.9.0 will contain other breaking changes.

I hope you will understand my point here.

**Comment by brutasse** [comment]
Hi @mlec1, and thank you for your feedback.

From https://semver.org/ which python-exoscale follows for the time being: "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

This is still the case, and we will bump to 1.x once we're ready to commit to API stability. I hope this addresses your concerns.
