### ISSUE TITLE
Handle multiple path parameters

### ISSUE THREAD

**Issue by thomas-chauvet** [exoscale/python-exoscale#58]
Hello,

I noticed that the `v2` part of the library does not handle multiple path parameters.

For instance when using:

```python

c = Client(api_key, api_secret, url="https://api-ch-gva-2.exoscale.com/v2")
c.update_dbaas_pg_connection_pool(
            connection_pool_name=connection_pool_name,
            service_name=dbaas_service_name,
            database_name=connection_pool_db,
            mode=connection_pool_mode,
            size=connection_pool_number,
        )
```

It will raise a `KeyError` because only the first parameter (`service_name`) will be given and not the two parameters needed for this route (`service_name` and `connection_pool_name`).

I've opened a PR to fix this: https://github.com/exoscale/python-exoscale/pull/57

**Comment by pierre-emmanuelJ** [comment]
Thanks a lot for your contribution!

A release is upcoming: https://github.com/exoscale/python-exoscale/pull/59

I close this one since your PR has been merged
